name: Proposition d'amélioration
description: Proposer une fonction ou une compatibilité
title: "[Idée] "
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: Besoin
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition
    validations:
      required: true
